// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB05Av9eLQ5iUQ15gsar7DTw8XVoz7_zLs',
    appId: '1:536857005848:android:7e6a5b12b9bca688fad86d',
    messagingSenderId: '536857005848',
    projectId: 'study-drive-2777e',
    storageBucket: 'study-drive-2777e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB05Av9eLQ5iUQ15gsar7DTw8XVoz7_zLs',
    appId:
        '1:536857005848:web:placeholder_app_id', // NOTE: Replace with actual Web App ID
    messagingSenderId: '536857005848',
    projectId: 'study-drive-2777e',
    authDomain: 'study-drive-2777e.firebaseapp.com',
    storageBucket: 'study-drive-2777e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB05Av9eLQ5iUQ15gsar7DTw8XVoz7_zLs',
    appId:
        '1:536857005848:web:placeholder_app_id', // NOTE: Replace with actual Windows App ID
    messagingSenderId: '536857005848',
    projectId: 'study-drive-2777e',
    authDomain: 'study-drive-2777e.firebaseapp.com',
    storageBucket: 'study-drive-2777e.firebasestorage.app',
  );
}
